default: &default
  adapter: postgresql
  host: ''
  encoding: unicode
  pool: <%= Integer(ENV['RAILS_MAX_THREADS'] || 5) %>

development:
  <<: *default
  database: useradmin_development

test:
  <<: *default
  database: useradmin_test

production:
  <<: *default
  database: useradmin_production
